https://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html

In [1]:
# Author: Robert Guthrie
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [44]:
lstm = nn.LSTM(3, 3)  # Input dim is 3, output dim is 3
inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5

# initialize the hidden state.
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)
    print(out)
    print(hidden)

tensor([[[0.1050, 0.6543, 0.1713]]], grad_fn=<StackBackward0>)
(tensor([[[0.1050, 0.6543, 0.1713]]], grad_fn=<StackBackward0>), tensor([[[0.2801, 1.1698, 0.2483]]], grad_fn=<StackBackward0>))
tensor([[[ 0.2358,  0.6308, -0.1244]]], grad_fn=<StackBackward0>)
(tensor([[[ 0.2358,  0.6308, -0.1244]]], grad_fn=<StackBackward0>), tensor([[[ 0.6330,  0.9679, -0.2342]]], grad_fn=<StackBackward0>))
tensor([[[ 0.0632,  0.0542, -0.4082]]], grad_fn=<StackBackward0>)
(tensor([[[ 0.0632,  0.0542, -0.4082]]], grad_fn=<StackBackward0>), tensor([[[ 0.2578,  0.0794, -0.5721]]], grad_fn=<StackBackward0>))
tensor([[[0.1992, 0.1467, 0.0903]]], grad_fn=<StackBackward0>)
(tensor([[[0.1992, 0.1467, 0.0903]]], grad_fn=<StackBackward0>), tensor([[[0.4422, 0.1805, 0.1576]]], grad_fn=<StackBackward0>))
tensor([[[0.1570, 0.2488, 0.2887]]], grad_fn=<StackBackward0>)
(tensor([[[0.1570, 0.2488, 0.2887]]], grad_fn=<StackBackward0>), tensor([[[0.3754, 0.2905, 0.5443]]], grad_fn=<StackBackward0>))


In [45]:
inputs = [torch.randn(1, 3) for _ in range(5)] 
inputs = torch.cat(inputs).view(5,1, -1)

In [46]:
# alternatively, we can do the entire sequence all at once.
# the first value returned by LSTM is all of the hidden states throughout
# the sequence. the second is just the most recent hidden state
# (compare the last slice of "out" with "hidden" below, they are the same)
# The reason for this is that:
# "out" will give you access to all hidden states in the sequence
# "hidden" will allow you to continue the sequence and backpropagate,
# by passing it as an argument  to the lstm at a later time
# Add the extra 2nd dimension
#inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5
#inputs = torch.cat(inputs).view(5,1,-1)
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))  # clean out hidden state
out, hidden = lstm(inputs, hidden,batch_first=True)


TypeError: forward() got an unexpected keyword argument 'batch_first'

In [42]:
inputs.shape

torch.Size([5, 1, 3])

In [ ]:
out

In [ ]:
hidden