https://jott.live/markdown/as_strided

In [1]:
import numpy as np

In [2]:
def as_strided_custom(x, size, stride, storage_offset=0):
    """
    간단한 as_strided 흉내내기 (numpy 버전)

    x: 원본 1차원 numpy 배열 (메모리)
    size: 결과 텐서 shape (tuple)
    stride: 각 차원 이동 시 메모리 점프 크기 (tuple)
    storage_offset: 메모리 시작 위치
    """
    # 결과 shape에 맞는 인덱스 좌표 생성
    idx = np.indices(size)  # 각 좌표의 인덱스 그리드
    offset = storage_offset

    # 좌표 * stride 를 더해 메모리 인덱스 계산
    mem_index = offset + sum(idx[d] * stride[d] for d in range(len(size)))

    # 원본 메모리에서 값 추출
    return x[mem_index]

In [3]:
# 예제: 3x3 행렬
base = np.arange(1, 10)   # [1..9]
x = base.reshape(3,3)
print("원본 행렬:\n", x)

원본 행렬:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# 좌상단 2x2 패치 추출 (stride=(3,1))
y = as_strided_custom(base, size=(2,2), stride=(3,1))
print("\nstride=(3,1), size=(2,2):\n", y)


stride=(3,1), size=(2,2):
 [[1 2]
 [4 5]]
